import { useEffect, useMemo, useState } from "react";
import { Lock, Plus, Sparkles } from "lucide-react";
import { base44 } from "@/api/base44Client";
import BirthDataSheet from "./BirthDataSheet";
import {
  getSunSign,
  getSunDegree,
  getRulingPlanet,
  getZodiacGlyph,
  getMoonPhase,
  prettyDateBritish,
  prettyDateShortBritish,
  prettyBirthday,
  ALL_ZODIAC,
} from "@/utils/astrology";

// ─────────────────────────────────────────────────────────────────────────────
// HoroscopeTab — full rebuild per femwell_lifestyle_demo.html lines 783-970.
//
// Sections rendered in MP-Horo-A:
//   1. Hero            — date · kicker · headline · narrative · pills · moon
//   2. Triad           — sun / moon / rising (moon + rising locked until BT)
//   3. Today's weather — power / pressure / trouble energy cards
//   4. Cycle × Moon    — intersection narrative + paired ring visuals
//   5. This week       — 4 transit cards
//
// Compatibility + Ask-the-Stars land in MP-Horo-B and MP-Horo-C.
//
// Data flow:
//   AstroProfile  ← per-user birth data, written via BirthDataSheet
//   HoroscopeReading ← one row per user per day, generated by
//                       `generateHoroscopeReading` (orchestrator daily job)
//
// When today's reading hasn't generated yet we fall back to deterministic
// scaffold text from the sun sign + cycle phase so the page never reads
// "Check back soon" again.
// ─────────────────────────────────────────────────────────────────────────────

const TODAY_ISO = () => new Date().toISOString().split("T")[0];

export default function HoroscopeTab(props) {
  // Props are optional — when this component is mounted standalone we load
  // UserProfile / LifestyleProfile ourselves. If the parent already has them
  // loaded it can pass them down to avoid a duplicate fetch.
  const [user, setUser] = useState(null);
  const [astro, setAstro] = useState(null);     // AstroProfile row
  const [reading, setReading] = useState(null); // HoroscopeReading row
  const [userProfileLocal, setUserProfileLocal] = useState(props.userProfile || null);
  const [lifestyleProfileLocal, setLifestyleProfileLocal] = useState(props.lifestyleProfile || null);
  const [loading, setLoading] = useState(true);
  const [sheetOpen, setSheetOpen] = useState(false);
  const userProfile = props.userProfile || userProfileLocal;
  const lifestyleProfile = props.lifestyleProfile || lifestyleProfileLocal;

  // ── Initial load ─────────────────────────────────────────────────────────
  useEffect(() => {
    let cancelled = false;
    (async () => {
      setLoading(true);
      try {
        const u = await base44.auth.me().catch(() => null);
        if (cancelled) return;
        setUser(u);

        if (!u?.id) { setLoading(false); return; }

        const [aps, readings, profiles, lpRows] = await Promise.all([
          base44.entities.AstroProfile.filter({ user_id: u.id }, undefined, 1).catch(() => []),
          base44.entities.HoroscopeReading.filter(
            { user_id: u.id, reading_date: TODAY_ISO() },
            "-created_date",
            1,
          ).catch(() => []),
          props.userProfile
            ? Promise.resolve([props.userProfile])
            : base44.entities.UserProfile.filter({ user_id: u.id }, undefined, 1).catch(() => []),
          props.lifestyleProfile
            ? Promise.resolve([props.lifestyleProfile])
            : base44.entities.LifestyleProfile.filter({ user_id: u.id }, undefined, 1).catch(() => []),
        ]);
        if (cancelled) return;

        const ap = (aps && aps[0]) || null;
        setAstro(ap);
        setReading((readings && readings[0]) || null);
        if (!props.userProfile) setUserProfileLocal((profiles && profiles[0]) || null);
        if (!props.lifestyleProfile) setLifestyleProfileLocal((lpRows && lpRows[0]) || null);

        // Fire-and-forget kick if we have a chart but no reading for today —
        // the orchestrator picks this up nightly but the user shouldn't have
        // to wait if it's their first open of the day.
        if (ap && (!readings || !readings[0])) {
          base44.functions
            .invoke("generateHoroscopeReading", { user_id: u.id })
            .then((res) => {
              if (cancelled) return;
              const next = res?.data?.reading || res?.reading || null;
              if (next) setReading(next);
            })
            .catch(() => {});
        }
      } finally {
        if (!cancelled) setLoading(false);
      }
    })();
    return () => { cancelled = true; };
  }, []);

  // ── Derived chart facts (shown even when reading hasn't generated) ──────
  const chart = useMemo(() => deriveChart(astro, userProfile), [astro, userProfile]);
  const cyclePhase = useMemo(() => derivePhase(userProfile), [userProfile]);
  const moon = useMemo(() => getMoonPhase(new Date()), []);

  if (loading) {
    return <div style={loadingStyle}>Reading the sky…</div>;
  }

  // ── No chart yet — show onboarding card ──────────────────────────────────
  if (!astro) {
    return (
      <div>
        <OnboardingCard onOpen={() => setSheetOpen(true)} />
        <BirthDataSheet
          open={sheetOpen}
          onClose={() => setSheetOpen(false)}
          userId={user?.id}
          initial={null}
          onSaved={(saved) => setAstro(saved)}
        />
      </div>
    );
  }

  return (
    <div>
      <Hero
        chart={chart}
        moon={moon}
        astro={astro}
        reading={reading}
      />
      <Triad
        chart={chart}
        astro={astro}
        reading={reading}
        onAddBirthTime={() => setSheetOpen(true)}
      />
      <Weather reading={reading} chart={chart} />
      <CycleMoon
        cyclePhase={cyclePhase}
        moon={moon}
        reading={reading}
      />
      <Transits reading={reading} />
      <Compatibility userId={user?.id} chart={chart} />

      <BirthDataSheet
        open={sheetOpen}
        onClose={() => setSheetOpen(false)}
        userId={user?.id}
        initial={astro}
        onSaved={(saved) => setAstro(saved)}
      />
    </div>
  );
}

// ─────────────────────────────────────────────────────────────────────────────
// Helpers
// ─────────────────────────────────────────────────────────────────────────────
function deriveChart(astro, userProfile) {
  const birthday =
    astro?.birth_date ||
    userProfile?.birthday ||
    userProfile?.date_of_birth ||
    null;
  const sun = astro?.sun_sign || getSunSign(birthday);
  const sunDegree = birthday ? getSunDegree(birthday) : null;
  return {
    birthday,
    sun,
    sunDegree,
    sunRuler: sun ? getRulingPlanet(sun) : null,
    sunGlyph: sun ? getZodiacGlyph(sun) : "✦",
    moonSign: astro?.moon_sign || null,
    risingSign: astro?.rising_sign || null,
    hasBirthTime: !!astro?.birth_time,
    place: astro?.birth_place || null,
    name: userProfile?.preferred_name || userProfile?.first_name || "",
  };
}

function derivePhase(userProfile) {
  // Mirror the existing util util/cyclePhase.js semantics; we just need a
  // label here, not a date math result. Fall back to null cleanly.
  if (!userProfile?.last_period_start_date) return null;
  const last = new Date(userProfile.last_period_start_date);
  const cycleLen = userProfile.cycle_avg_length || 28;
  const periodLen = userProfile.period_length || 5;
  const diffDays = Math.floor((Date.now() - last.getTime()) / 86400000);
  const day = ((diffDays % cycleLen) + cycleLen) % cycleLen + 1;
  if (day <= periodLen) return "menstrual";
  if (day <= 13) return "follicular";
  if (day <= 16) return "ovulatory";
  return "luteal";
}

// ─────────────────────────────────────────────────────────────────────────────
// Section 1 — Hero
// ─────────────────────────────────────────────────────────────────────────────
function Hero({ chart, moon, astro, reading }) {
  const kicker = (() => {
    const parts = [];
    if (chart.name) parts.push(`For ${chart.name}`);
    if (chart.birthday) parts.push(`born ${prettyBirthday(chart.birthday)}`);
    if (chart.place) parts.push(chart.place);
    return parts.join(" · ") || "Your chart";
  })();

  const headline = reading?.headline ||
    fallbackHeadline(chart.sun, moon);
  const narrative = reading?.narrative ||
    fallbackNarrative(chart.sun, moon);

  return (
    <div style={heroShellStyle}>
      <div style={heroOverlayStyle} />
      <div style={heroContentStyle}>
        <div style={heroLeftStyle}>
          <p style={heroDateStyle}>{prettyDateBritish(new Date())}</p>
          <p style={heroKickerStyle}>{kicker}</p>
          <h1 style={heroHeadStyle} dangerouslySetInnerHTML={{ __html: renderEm(headline) }} />
          <p style={heroBodyStyle}>{narrative}</p>
          <div style={heroPillsStyle}>
            {chart.sun && <Pill glow>☉ {chart.sun} sun</Pill>}
            <Pill>☽ {moon.short} · {moon.illumination}%</Pill>
            {reading?.mercury_pill && <Pill>☿ {reading.mercury_pill}</Pill>}
            {!reading?.mercury_pill && chart.sunRuler && (
              <Pill>{rulerGlyph(chart.sunRuler)} {chart.sunRuler}</Pill>
            )}
          </div>
        </div>
        <div style={heroVisualStyle} aria-hidden="true">
          <MoonVisual moon={moon} />
          <p style={moonLabelStyle}>{moon.short} — {moon.waxing ? "becoming" : "releasing"}</p>
        </div>
      </div>
    </div>
  );
}

function Pill({ glow, children }) {
  return (
    <span style={{ ...pillStyle, ...(glow ? pillGlowStyle : {}) }}>{children}</span>
  );
}

function MoonVisual({ moon }) {
  // A simple 2-layer moon: cream disc + plum overlay sliding across.
  const phase = moon.position;
  // Cosine-based overlay offset so the terminator looks natural.
  const offset = Math.cos(2 * Math.PI * phase);
  const isWaxing = moon.waxing;
  return (
    <div style={moonDiscStyle}>
      <div
        style={{
          ...moonOverlayStyle,
          transform: `translateX(${(isWaxing ? -offset : offset) * 50}%)`,
        }}
      />
    </div>
  );
}

function fallbackHeadline(sun, moon) {
  if (!sun) return `The <em>moon</em> is ${moon.short.toLowerCase()}, the day is yours`;
  const ruler = getRulingPlanet(sun);
  return `${ruler} <em>steadies</em>, the moon <em>listens</em>`;
}
function fallbackNarrative(sun, moon) {
  const ruler = sun ? getRulingPlanet(sun) : "your ruler";
  return `Today's reading is being written. While it arrives, your chart is reporting a ${moon.short.toLowerCase()} sky and ${ruler} doing its quiet work. Move gently. Notice what your body is saying before the day asks for an answer.`;
}

// ─────────────────────────────────────────────────────────────────────────────
// Section 2 — Triad
// ─────────────────────────────────────────────────────────────────────────────
function Triad({ chart, astro, reading, onAddBirthTime }) {
  const sunDesc = reading?.triad_sun_desc || fallbackTriadSunDesc(chart.sun);
  const moonDesc = reading?.triad_moon_desc;
  const risingDesc = reading?.triad_rising_desc;
  const hasBT = !!astro?.birth_time;

  return (
    <div style={{ marginTop: 32 }}>
      <SectionHead title="Your" emphasis="triad" link={hasBT ? null : "Add birth time & place to unlock all three →"} />
      <div style={triadRowStyle}>
        <TriadCard
          glyph={chart.sunGlyph || "☉"}
          label="Sun · self"
          sign={chart.sun ? `${chart.sun}${chart.sunDegree != null ? ` · ${chart.sunDegree}°` : ""}` : "—"}
          desc={sunDesc}
          locked={false}
        />
        <TriadCard
          glyph="☽"
          label="Moon · inner life"
          sign={chart.moonSign ? chart.moonSign : "— add time"}
          desc={moonDesc || "Your moon sign shows how you feel things, how you soothe yourself, what makes you feel safe."}
          locked={!hasBT || !chart.moonSign}
          onUnlock={onAddBirthTime}
        />
        <TriadCard
          glyph="↗"
          label="Rising · mask"
          sign={chart.risingSign ? chart.risingSign : "— add time"}
          desc={risingDesc || "The self people meet first — how you enter a room. Only your birth time can unlock it."}
          locked={!hasBT || !chart.risingSign}
          onUnlock={onAddBirthTime}
        />
      </div>
    </div>
  );
}

function TriadCard({ glyph, label, sign, desc, locked, onUnlock }) {
  return (
    <div style={{ ...triadCardStyle, opacity: locked ? 0.7 : 1 }}>
      <div style={triadGlyphStyle}>{glyph}</div>
      <p style={triadLabelStyle}>{label}</p>
      <p style={triadSignStyle}>{sign}</p>
      <p style={triadDescStyle}>{desc}</p>
      {locked && (
        <button type="button" onClick={onUnlock} style={triadUnlockBtnStyle}>
          <Plus size={12} /> Add birth time
        </button>
      )}
    </div>
  );
}

function fallbackTriadSunDesc(sun) {
  const m = {
    Aries: "First in. The match that lights the room — and the one that needs to be the lit one.",
    Taurus: "Slow on purpose. You build pleasure into the spine of the day.",
    Gemini: "Curious, double-minded. You speak yourself into knowing what you think.",
    Cancer: "You feel the room before anyone speaks. Your shell is also your softest skin.",
    Leo: "Warm sovereign. You expand others by simply being seen.",
    Virgo: "Patterns, ratios, repair. You love by tidying the edges of someone's life.",
    Libra: "Air with manners. You compose rooms — and yourself — in pairs.",
    Scorpio: "All depth. You don't waste your attention on shallow tide-pools.",
    Sagittarius: "Long view. You're the friend who buys the flight before booking the room.",
    Capricorn: "Slow ladder. The mountain you climb is real and it is also yours.",
    Aquarius: "Future-tense. You see the system before the people inside it.",
    Pisces: "Tide. Whatever you feel today will move, and you with it.",
  };
  return m[sun] || "Your sun sign will whisper here once your chart is loaded.";
}

// ─────────────────────────────────────────────────────────────────────────────
// Section 3 — Today's weather
// ─────────────────────────────────────────────────────────────────────────────
function Weather({ reading, chart }) {
  const power = reading?.power_title
    ? { title: reading.power_title, body: reading.power_body }
    : fallbackWeatherCard("power", chart);
  const pressure = reading?.pressure_title
    ? { title: reading.pressure_title, body: reading.pressure_body }
    : fallbackWeatherCard("pressure", chart);
  const trouble = reading?.trouble_title
    ? { title: reading.trouble_title, body: reading.trouble_body }
    : fallbackWeatherCard("trouble", chart);

  return (
    <div style={{ marginTop: 32 }}>
      <SectionHead title="Today's" emphasis="weather" />
      <div style={weatherRowStyle}>
        <WeatherCard kind="power" title={power.title} body={power.body} />
        <WeatherCard kind="pressure" title={pressure.title} body={pressure.body} />
        <WeatherCard kind="trouble" title={trouble.title} body={trouble.body} />
      </div>
    </div>
  );
}

const WEATHER_META = {
  power:    { glyph: "✦", label: "Power",    color: "var(--rose-primary, #D45E52)" },
  pressure: { glyph: "◑", label: "Pressure", color: "var(--gold, #B89E6A)" },
  trouble:  { glyph: "◉", label: "Trouble",  color: "var(--plum-deep, #4A2D40)" },
};
function WeatherCard({ kind, title, body }) {
  const meta = WEATHER_META[kind];
  return (
    <div style={{ ...weatherCardStyle, borderTopColor: meta.color }}>
      <p style={{ ...weatherLabelStyle, color: meta.color }}>{meta.glyph} {meta.label}</p>
      <p style={weatherTitleStyle}>{title}</p>
      <p style={weatherBodyStyle}>{body}</p>
    </div>
  );
}

function fallbackWeatherCard(kind, chart) {
  const sun = chart?.sun || "your sun";
  const m = {
    power: {
      title: "One clear sentence",
      body: `Your reading is being written. While you wait, ask yourself what ${sun} would say plainly today.`,
    },
    pressure: {
      title: "Don't over-explain",
      body: "Today is fine if you respond with fewer words than feels safe.",
    },
    trouble: {
      title: "Small slights, big stories",
      body: "A two-line message will feel like a novel. Let it sit for twenty minutes before you answer.",
    },
  };
  return m[kind];
}

// ─────────────────────────────────────────────────────────────────────────────
// Section 4 — Cycle × Moon intersection
// ─────────────────────────────────────────────────────────────────────────────
function CycleMoon({ cyclePhase, moon, reading }) {
  const headline = reading?.cycle_moon_headline || defaultCycleMoonHeadline(cyclePhase, moon);
  const body = reading?.cycle_moon_body || defaultCycleMoonBody(cyclePhase, moon);
  return (
    <div style={intersectShellStyle}>
      <div style={{ flex: "1 1 320px" }}>
        <p style={intersectEyebrowStyle}>Your cycle · meeting the sky</p>
        <h3 style={intersectHeadStyle} dangerouslySetInnerHTML={{ __html: renderEm(headline) }} />
        <p style={intersectBodyStyle}>{body}</p>
      </div>
      <div style={ringsRowStyle} aria-hidden="true">
        <RingWrap label="Sky" glyph={moon.glyph} />
        <RingWrap label="Body" glyph={cyclePhaseGlyph(cyclePhase)} />
      </div>
    </div>
  );
}

function RingWrap({ label, glyph }) {
  return (
    <div style={ringWrapStyle}>
      <div style={ringStyle}>{glyph}</div>
      <p style={ringLabelStyle}>{label}</p>
    </div>
  );
}

function cyclePhaseGlyph(phase) {
  switch (phase) {
    case "menstrual": return "◐";
    case "follicular": return "◔";
    case "ovulatory": return "○";
    case "luteal": return "◕";
    default: return "·";
  }
}
function defaultCycleMoonHeadline(cycle, moon) {
  if (!cycle) return `A <em>${moon.short.toLowerCase()}</em> over the city`;
  const c = cycle.charAt(0).toUpperCase() + cycle.slice(1);
  return `${c} body under a <em>${moon.short.toLowerCase()}</em>`;
}
function defaultCycleMoonBody(cycle, moon) {
  if (!cycle) {
    return `The moon is ${moon.short.toLowerCase()} and your cycle phase isn't tracked here yet — log a cycle in Track and the sky will start speaking to your body.`;
  }
  const phaseText = {
    menstrual: "Your body is shedding. A bright moon will feel louder than usual.",
    follicular: "Your body is rising. Sky and skin both want gentle action.",
    ovulatory: "Your body is peaking. Conversation will move faster than thought.",
    luteal: "Your body is settling. Edit, refine, finish — don't start.",
  }[cycle];
  return `${phaseText} The ${moon.short.toLowerCase()} sky says: ${moon.waxing ? "build" : "release"}. Match your day to that small instruction and the rest looks after itself.`;
}

// ─────────────────────────────────────────────────────────────────────────────
// Section 5 — This week (transits)
// ─────────────────────────────────────────────────────────────────────────────
function Transits({ reading }) {
  const transits = Array.isArray(reading?.transits_json) && reading.transits_json.length > 0
    ? reading.transits_json
    : fallbackTransits();
  return (
    <div style={{ marginTop: 32, marginBottom: 24 }}>
      <SectionHead title="This" emphasis="week" link="7-day view" />
      <div style={transitsColStyle}>
        {transits.slice(0, 4).map((t, i) => (
          <TransitCard key={t.id || `t-${i}`} transit={t} />
        ))}
      </div>
    </div>
  );
}

function TransitCard({ transit }) {
  return (
    <div style={transitCardStyle}>
      <div style={transitGlyphStyle}>{transit.glyph || "✦"}</div>
      <div style={{ flex: 1 }}>
        <p style={transitWhenStyle}>{prettyTransitDate(transit.when) || transit.when_label || ""}</p>
        <p style={transitTitleStyle}>{transit.title || "Transit"}</p>
        <p style={transitDescStyle}>{transit.desc || transit.body || ""}</p>
      </div>
    </div>
  );
}

function prettyTransitDate(when) {
  if (!when) return "";
  // Accept ISO date strings; otherwise pass through.
  if (/^\d{4}-\d{2}-\d{2}/.test(when)) return prettyDateShortBritish(when);
  return when;
}

function fallbackTransits() {
  const today = new Date();
  const inDays = (n) => {
    const d = new Date(today);
    d.setDate(d.getDate() + n);
    return d.toISOString().split("T")[0];
  };
  return [
    {
      id: "fb-1", glyph: "☉",
      when: inDays(0),
      title: "Your reading is being written",
      desc: "We're generating your transits in the background. They'll appear by the next time you open the app.",
    },
    {
      id: "fb-2", glyph: "☽",
      when: inDays(3),
      title: "Moon shifts phase",
      desc: "The sky's tone changes mid-week. Notice your sleep around then.",
    },
    {
      id: "fb-3", glyph: "♀",
      when: inDays(5),
      title: "Venus moves",
      desc: "Relational weather shifts. Plan a small kindness, not a big gesture.",
    },
    {
      id: "fb-4", glyph: "☿",
      when: inDays(7),
      title: "Mercury reports in",
      desc: "Your ruler will adjust. Watch your word count for a day.",
    },
  ];
}

// ─────────────────────────────────────────────────────────────────────────────
// Section 6 — Compatibility
// ─────────────────────────────────────────────────────────────────────────────
function Compatibility({ userId, chart }) {
  const [name, setName] = useState("");
  const [birthday, setBirthday] = useState("");
  const [reading, setReading] = useState(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");
  const [history, setHistory] = useState([]); // last 3 readings for this user

  // Load last few readings to show as chips
  useEffect(() => {
    if (!userId) return;
    let cancelled = false;
    (async () => {
      try {
        const rows = await base44.entities.CompatibilityReading.filter(
          { user_id: userId },
          "-created_date",
          3,
        ).catch(() => []);
        if (cancelled) return;
        setHistory(Array.isArray(rows) ? rows : []);
      } catch { /* silent */ }
    })();
    return () => { cancelled = true; };
  }, [userId]);

  const run = async () => {
    setError("");
    if (!userId) { setError("Sign in to run a reading."); return; }
    if (!birthday) { setError("Their birthday is needed."); return; }
    setLoading(true);
    try {
      const res = await base44.functions.invoke("generateCompatibility", {
        user_id: userId,
        their_name: name.trim(),
        their_birthday: birthday,
      });
      const row = res?.data?.reading || res?.reading || null;
      if (!row) {
        setError(res?.data?.error || res?.error || "Couldn't read this pairing.");
      } else {
        setReading(row);
        // Refresh chip history
        setHistory((prev) => {
          const filtered = prev.filter((r) => r.id !== row.id);
          return [row, ...filtered].slice(0, 3);
        });
      }
    } catch (e) {
      setError(e?.message || "Couldn't read this pairing.");
    } finally {
      setLoading(false);
    }
  };

  const openHistory = (row) => {
    setName(row.their_name || "");
    setBirthday(row.their_birthday || "");
    setReading(row);
    setError("");
  };

  return (
    <div style={{ marginTop: 32 }}>
      <div style={compatHeadStyle}>
        <div>
          <h3 style={sectionTitleStyle}>
            Compatibility <em style={{ fontStyle: "italic", color: "var(--rose-primary, #D45E52)" }}>reading</em>
          </h3>
          <p style={compatSubStyle}>
            Try it with a friend, a partner, a crush — see where your charts meet.
          </p>
        </div>
        {chart.sun && (
          <span style={compatYouStyle}>
            You: {chart.sun}{chart.birthday ? ` · ${prettyBirthday(chart.birthday)}` : ""}
          </span>
        )}
      </div>

      <div style={compatFormStyle}>
        <div style={compatFieldStyle}>
          <label style={compatLabelStyle} htmlFor="cp-name">Their name</label>
          <input
            id="cp-name"
            type="text"
            placeholder="e.g. Sam"
            value={name}
            onChange={(e) => setName(e.target.value)}
            style={compatInputStyle}
          />
        </div>
        <div style={compatFieldStyle}>
          <label style={compatLabelStyle} htmlFor="cp-date">Their birthday</label>
          <input
            id="cp-date"
            type="date"
            value={birthday}
            onChange={(e) => setBirthday(e.target.value)}
            style={compatInputStyle}
          />
        </div>
        <button
          type="button"
          onClick={run}
          disabled={loading || !birthday}
          style={compatRunBtnStyle}
        >
          {loading ? "Reading…" : "✦ Read us"}
        </button>
      </div>

      {history.length > 0 && (
        <div style={historyRowStyle}>
          {history.map((r) => (
            <button
              key={r.id}
              type="button"
              onClick={() => openHistory(r)}
              style={{
                ...historyChipStyle,
                ...(reading?.id === r.id ? historyChipActiveStyle : {}),
              }}
            >
              {(r.their_name || r.their_sun_sign || "Reading")} · {r.score}
            </button>
          ))}
        </div>
      )}

      {error && <p style={compatErrorStyle}>{error}</p>}

      {reading && (
        <div style={compatResultStyle}>
          <div style={compatScoreRowStyle}>
            <div style={compatScoreBigStyle}>{reading.score}</div>
            <div>
              <p style={compatScoreLabelStyle}>Your synastry</p>
              <p style={compatScoreDescStyle}>{reading.label}</p>
            </div>
          </div>
          {reading.narrative && (
            <p style={compatNarrativeStyle}>{reading.narrative}</p>
          )}
          <div style={dimsRowStyle}>
            <Dim label="Talk"  val={reading.talk_score} />
            <Dim label="Touch" val={reading.touch_score} />
            <Dim label="Trust" val={reading.trust_score} />
            <Dim label="Grow"  val={reading.grow_score} />
          </div>
        </div>
      )}
    </div>
  );
}

function Dim({ label, val }) {
  const pct = Math.max(0, Math.min(100, Number(val) || 0));
  return (
    <div style={dimCellStyle}>
      <div style={dimBarStyle}>
        <div style={{ ...dimFillStyle, width: `${pct}%` }} />
      </div>
      <p style={dimLabelStyle}>{label}</p>
      <p style={dimValStyle}>{pct}</p>
    </div>
  );
}

// ─────────────────────────────────────────────────────────────────────────────
// Onboarding card (shown when no AstroProfile yet)
// ─────────────────────────────────────────────────────────────────────────────
function OnboardingCard({ onOpen }) {
  return (
    <div style={onboardingStyle}>
      <div style={onboardingGradientStyle} aria-hidden="true" />
      <Sparkles size={28} style={{ color: "var(--cream, #FAF4EA)", position: "relative", zIndex: 1 }} />
      <h2 style={onboardingTitleStyle}>Read me the sky</h2>
      <p style={onboardingBodyStyle}>
        FemWell writes you a daily reading based on your chart and your cycle. To start, we need your birth date. Birth time and place unlock your moon and rising too.
      </p>
      <button type="button" onClick={onOpen} style={onboardingBtnStyle}>
        Unlock my chart
      </button>
    </div>
  );
}

// ─────────────────────────────────────────────────────────────────────────────
// Shared bits
// ─────────────────────────────────────────────────────────────────────────────
function SectionHead({ title, emphasis, link }) {
  return (
    <div style={sectionHeadStyle}>
      <h2 style={sectionTitleStyle}>
        {title} <em style={{ fontStyle: "italic", color: "var(--rose-primary, #D45E52)" }}>{emphasis}</em>
      </h2>
      {link && <span style={sectionLinkStyle}>{link}</span>}
    </div>
  );
}

function renderEm(text) {
  // Lightweight inline <em> renderer. Demo headlines use *word* in some
  // places — we accept either *word* or actual <em>word</em>. Strict HTML
  // escape on everything else.
  if (!text) return "";
  const escaped = String(text)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");
  return escaped
    .replace(/&lt;em&gt;(.*?)&lt;\/em&gt;/g, '<em style="font-style:italic;">$1</em>')
    .replace(/\*(.+?)\*/g, '<em style="font-style:italic;">$1</em>');
}

function rulerGlyph(planet) {
  const m = { Sun: "☉", Moon: "☽", Mercury: "☿", Venus: "♀", Mars: "♂", Jupiter: "♃", Saturn: "♄", Uranus: "♅", Neptune: "♆", Pluto: "♇" };
  return m[planet] || "✦";
}

// ─────────────────────────────────────────────────────────────────────────────
// Styles
// ─────────────────────────────────────────────────────────────────────────────
const loadingStyle = {
  padding: "60px 24px",
  textAlign: "center",
  fontFamily: "'Inter', sans-serif",
  fontSize: 14,
  color: "var(--plum-mute, #6b4a56)",
};

// Hero
const heroShellStyle = {
  position: "relative",
  borderRadius: 22,
  overflow: "hidden",
  padding: "32px 28px",
  background: "radial-gradient(circle at 20% 30%, #3a2a4c 0%, #221a2e 55%, #15101e 100%)",
  color: "var(--cream, #FAF4EA)",
  boxShadow: "0 2px 4px rgba(43,30,22,0.10), 0 12px 32px rgba(43,30,22,0.18)",
  marginBottom: 8,
};
const heroOverlayStyle = {
  position: "absolute", inset: 0,
  background:
    "radial-gradient(circle at 80% 18%, rgba(232,196,208,0.18) 0%, rgba(232,196,208,0) 30%)," +
    "radial-gradient(circle at 12% 72%, rgba(150,120,180,0.18) 0%, rgba(150,120,180,0) 35%)",
  pointerEvents: "none",
};
const heroContentStyle = {
  position: "relative",
  display: "flex",
  gap: 24,
  flexWrap: "wrap",
  alignItems: "flex-start",
};
const heroLeftStyle = { flex: "1 1 280px", minWidth: 260 };
const heroDateStyle = {
  fontFamily: "'Inter', sans-serif",
  fontSize: 11, fontWeight: 700,
  letterSpacing: "0.14em",
  textTransform: "uppercase",
  color: "rgba(247,239,225,0.72)",
  margin: "0 0 6px",
};
const heroKickerStyle = {
  fontFamily: "'Inter', sans-serif",
  fontSize: 12, fontWeight: 500,
  color: "rgba(247,239,225,0.66)",
  margin: "0 0 14px",
  letterSpacing: "0.02em",
};
const heroHeadStyle = {
  fontFamily: "'Fraunces', serif",
  fontWeight: 300,
  fontSize: "clamp(28px, 5vw, 38px)",
  lineHeight: 1.1,
  letterSpacing: "-0.015em",
  color: "var(--cream, #FAF4EA)",
  margin: "0 0 14px",
};
const heroBodyStyle = {
  fontFamily: "'Inter', sans-serif",
  fontSize: 14,
  lineHeight: 1.6,
  color: "rgba(247,239,225,0.88)",
  margin: "0 0 18px",
};
const heroPillsStyle = { display: "flex", flexWrap: "wrap", gap: 8 };
const heroVisualStyle = {
  flex: "0 0 180px",
  display: "flex", flexDirection: "column", alignItems: "center", gap: 10,
};
const moonLabelStyle = {
  fontFamily: "'Fraunces', serif",
  fontStyle: "italic",
  fontSize: 12,
  color: "rgba(247,239,225,0.72)",
  margin: 0,
};
const moonDiscStyle = {
  position: "relative",
  width: 130, height: 130,
  borderRadius: "50%",
  background:
    "radial-gradient(circle at 35% 30%, #F0E6D2 0%, #C9B79E 55%, #6B5B47 100%)",
  overflow: "hidden",
  boxShadow: "0 0 30px rgba(232,196,208,0.18), inset 0 0 20px rgba(0,0,0,0.18)",
};
const moonOverlayStyle = {
  position: "absolute",
  inset: 0,
  background: "linear-gradient(90deg, rgba(15,10,22,0.88) 50%, transparent 50.1%)",
};
const pillStyle = {
  display: "inline-flex",
  alignItems: "center",
  fontFamily: "'Inter', sans-serif",
  fontSize: 11, fontWeight: 600,
  letterSpacing: "0.06em",
  textTransform: "uppercase",
  color: "rgba(247,239,225,0.88)",
  background: "rgba(247,239,225,0.10)",
  border: "1px solid rgba(247,239,225,0.18)",
  padding: "5px 10px",
  borderRadius: 9999,
};
const pillGlowStyle = {
  background: "rgba(232,196,208,0.22)",
  borderColor: "rgba(232,196,208,0.40)",
  color: "var(--cream, #FAF4EA)",
  boxShadow: "0 0 14px rgba(232,196,208,0.30)",
};

// Section heads
const sectionHeadStyle = {
  display: "flex",
  alignItems: "baseline",
  justifyContent: "space-between",
  margin: "0 0 12px",
  flexWrap: "wrap",
  gap: 8,
};
const sectionTitleStyle = {
  fontFamily: "'Fraunces', serif",
  fontWeight: 400,
  fontSize: 22,
  color: "var(--plum-deep, #2b1e16)",
  margin: 0,
};
const sectionLinkStyle = {
  fontFamily: "'Inter', sans-serif",
  fontSize: 12,
  fontWeight: 500,
  color: "var(--plum-mute, #6b4a56)",
};

// Triad
const triadRowStyle = {
  display: "grid",
  gridTemplateColumns: "repeat(auto-fit, minmax(220px, 1fr))",
  gap: 12,
};
const triadCardStyle = {
  position: "relative",
  background: "var(--cream, #FAF4EA)",
  border: "1px solid var(--ink-line, rgba(43,30,22,0.10))",
  borderRadius: 18,
  padding: "20px 18px 22px",
  boxShadow:
    "0 1px 2px rgba(43,30,22,0.04), 0 4px 12px rgba(43,30,22,0.06)",
};
const triadGlyphStyle = {
  fontFamily: "'Fraunces', serif",
  fontSize: 30,
  color: "var(--rose-primary, #D45E52)",
  marginBottom: 8,
};
const triadLabelStyle = {
  fontFamily: "'Inter', sans-serif",
  fontSize: 11, fontWeight: 700,
  letterSpacing: "0.12em",
  textTransform: "uppercase",
  color: "var(--plum-mute, #6b4a56)",
  margin: "0 0 4px",
};
const triadSignStyle = {
  fontFamily: "'Fraunces', serif",
  fontSize: 18,
  fontWeight: 500,
  color: "var(--plum-deep, #2b1e16)",
  margin: "0 0 8px",
};
const triadDescStyle = {
  fontFamily: "'Inter', sans-serif",
  fontSize: 13,
  lineHeight: 1.55,
  color: "var(--plum-mute, #6b4a56)",
  margin: 0,
};
const triadUnlockBtnStyle = {
  display: "inline-flex", alignItems: "center", gap: 6,
  fontFamily: "'Inter', sans-serif",
  fontSize: 12, fontWeight: 600,
  color: "var(--rose-primary, #D45E52)",
  background: "transparent",
  border: "1px dashed var(--rose-primary, #D45E52)",
  borderRadius: 9999,
  padding: "6px 12px",
  marginTop: 12,
  cursor: "pointer",
};

// Weather
const weatherRowStyle = {
  display: "grid",
  gridTemplateColumns: "repeat(auto-fit, minmax(220px, 1fr))",
  gap: 12,
};
const weatherCardStyle = {
  background: "var(--cream, #FAF4EA)",
  border: "1px solid var(--ink-line, rgba(43,30,22,0.10))",
  borderTop: "3px solid var(--rose-primary, #D45E52)",
  borderRadius: 16,
  padding: "16px 18px 18px",
  boxShadow: "0 1px 2px rgba(43,30,22,0.04)",
};
const weatherLabelStyle = {
  fontFamily: "'Inter', sans-serif",
  fontSize: 11, fontWeight: 700,
  letterSpacing: "0.12em",
  textTransform: "uppercase",
  margin: "0 0 8px",
};
const weatherTitleStyle = {
  fontFamily: "'Fraunces', serif",
  fontStyle: "italic",
  fontWeight: 400,
  fontSize: 17,
  color: "var(--plum-deep, #2b1e16)",
  margin: "0 0 6px",
};
const weatherBodyStyle = {
  fontFamily: "'Inter', sans-serif",
  fontSize: 13,
  lineHeight: 1.55,
  color: "var(--plum-mute, #6b4a56)",
  margin: 0,
};

// Cycle × Moon
const intersectShellStyle = {
  display: "flex",
  alignItems: "center",
  gap: 24,
  flexWrap: "wrap",
  background:
    "linear-gradient(135deg, rgba(232,196,208,0.20), rgba(199,176,222,0.16))",
  border: "1px solid var(--ink-line, rgba(43,30,22,0.08))",
  borderRadius: 22,
  padding: "22px 22px",
  marginTop: 32,
};
const intersectEyebrowStyle = {
  fontFamily: "'Inter', sans-serif",
  fontSize: 11, fontWeight: 700,
  letterSpacing: "0.14em",
  textTransform: "uppercase",
  color: "var(--rose-primary, #D45E52)",
  margin: "0 0 6px",
};
const intersectHeadStyle = {
  fontFamily: "'Fraunces', serif",
  fontWeight: 400,
  fontSize: 22,
  color: "var(--plum-deep, #2b1e16)",
  margin: "0 0 8px",
  letterSpacing: "-0.01em",
};
const intersectBodyStyle = {
  fontFamily: "'Inter', sans-serif",
  fontSize: 14,
  lineHeight: 1.55,
  color: "var(--plum-mute, #6b4a56)",
  margin: 0,
};
const ringsRowStyle = { display: "flex", gap: 12, alignItems: "center" };
const ringWrapStyle = { display: "flex", flexDirection: "column", alignItems: "center", gap: 6 };
const ringStyle = {
  width: 64, height: 64,
  borderRadius: "50%",
  border: "1.5px solid var(--plum-mute, #6b4a56)",
  display: "flex", alignItems: "center", justifyContent: "center",
  fontFamily: "'Fraunces', serif",
  fontSize: 24,
  color: "var(--plum-deep, #2b1e16)",
  background: "rgba(255,255,255,0.32)",
};
const ringLabelStyle = {
  fontFamily: "'Inter', sans-serif",
  fontSize: 10, fontWeight: 700,
  letterSpacing: "0.10em",
  textTransform: "uppercase",
  color: "var(--plum-mute, #6b4a56)",
  margin: 0,
};

// Transits
const transitsColStyle = { display: "flex", flexDirection: "column", gap: 10 };
const transitCardStyle = {
  display: "flex",
  alignItems: "flex-start",
  gap: 14,
  background: "var(--cream, #FAF4EA)",
  border: "1px solid var(--ink-line, rgba(43,30,22,0.10))",
  borderRadius: 16,
  padding: "14px 16px",
};
const transitGlyphStyle = {
  fontFamily: "'Fraunces', serif",
  fontSize: 26,
  color: "var(--rose-primary, #D45E52)",
  width: 36,
  textAlign: "center",
};
const transitWhenStyle = {
  fontFamily: "'Inter', sans-serif",
  fontSize: 11, fontWeight: 700,
  letterSpacing: "0.12em",
  textTransform: "uppercase",
  color: "var(--plum-mute, #6b4a56)",
  margin: "0 0 2px",
};
const transitTitleStyle = {
  fontFamily: "'Fraunces', serif",
  fontWeight: 500,
  fontSize: 16,
  color: "var(--plum-deep, #2b1e16)",
  margin: "0 0 4px",
};
const transitDescStyle = {
  fontFamily: "'Inter', sans-serif",
  fontSize: 13,
  lineHeight: 1.55,
  color: "var(--plum-mute, #6b4a56)",
  margin: 0,
};

// Compatibility section
const compatHeadStyle = {
  display: "flex",
  alignItems: "flex-start",
  justifyContent: "space-between",
  gap: 12,
  marginBottom: 12,
  flexWrap: "wrap",
};
const compatSubStyle = {
  fontFamily: "'Inter', sans-serif",
  fontSize: 13,
  color: "var(--plum-mute, #6b4a56)",
  margin: "6px 0 0",
  lineHeight: 1.5,
};
const compatYouStyle = {
  fontFamily: "'Inter', sans-serif",
  fontSize: 11,
  fontWeight: 600,
  letterSpacing: "0.04em",
  color: "var(--plum-mute, #6b4a56)",
  background: "var(--cream-2, rgba(43,30,22,0.05))",
  padding: "5px 12px",
  borderRadius: 9999,
  alignSelf: "flex-start",
};
const compatFormStyle = {
  display: "grid",
  gridTemplateColumns: "1fr 1fr auto",
  gap: 10,
  alignItems: "end",
  marginBottom: 12,
};
const compatFieldStyle = { display: "flex", flexDirection: "column", minWidth: 0 };
const compatLabelStyle = {
  fontFamily: "'Inter', sans-serif",
  fontSize: 11,
  fontWeight: 600,
  letterSpacing: "0.04em",
  color: "var(--plum-deep, #2b1e16)",
  marginBottom: 5,
};
const compatInputStyle = {
  fontFamily: "'Inter', sans-serif",
  fontSize: 14,
  padding: "10px 12px",
  borderRadius: 12,
  border: "1px solid var(--ink-line, rgba(43,30,22,0.12))",
  background: "var(--cream-2, rgba(255,255,255,0.6))",
  color: "var(--plum-deep, #2b1e16)",
  minHeight: 44,
  width: "100%",
  boxSizing: "border-box",
};
const compatRunBtnStyle = {
  fontFamily: "'Inter', sans-serif",
  fontWeight: 600,
  fontSize: 13,
  color: "var(--cream, #FAF4EA)",
  background: "var(--rose-primary, #D45E52)",
  border: "none",
  borderRadius: 9999,
  padding: "12px 18px",
  cursor: "pointer",
  minHeight: 44,
  whiteSpace: "nowrap",
  boxShadow: "0 2px 8px rgba(212,94,82,0.30)",
};
const historyRowStyle = {
  display: "flex",
  flexWrap: "wrap",
  gap: 6,
  margin: "0 0 12px",
};
const historyChipStyle = {
  fontFamily: "'Inter', sans-serif",
  fontSize: 11,
  fontWeight: 600,
  letterSpacing: "0.03em",
  color: "var(--plum-mute, #6b4a56)",
  background: "transparent",
  border: "1px solid var(--ink-line, rgba(43,30,22,0.12))",
  borderRadius: 9999,
  padding: "5px 12px",
  cursor: "pointer",
  minHeight: 30,
};
const historyChipActiveStyle = {
  color: "var(--cream, #FAF4EA)",
  background: "var(--plum-deep, #2b1e16)",
  borderColor: "var(--plum-deep, #2b1e16)",
};
const compatErrorStyle = {
  fontFamily: "'Inter', sans-serif",
  fontSize: 12,
  color: "#A0312A",
  background: "rgba(160,49,42,0.10)",
  padding: "8px 12px",
  borderRadius: 10,
  margin: "0 0 12px",
};
const compatResultStyle = {
  background: "var(--cream, #FAF4EA)",
  border: "1px solid var(--ink-line, rgba(43,30,22,0.10))",
  borderRadius: 18,
  padding: "20px 22px 22px",
  boxShadow: "0 1px 2px rgba(43,30,22,0.04), 0 6px 18px rgba(43,30,22,0.06)",
};
const compatScoreRowStyle = {
  display: "flex",
  alignItems: "center",
  gap: 18,
  marginBottom: 14,
};
const compatScoreBigStyle = {
  fontFamily: "'Fraunces', serif",
  fontWeight: 300,
  fontSize: 56,
  lineHeight: 1,
  color: "var(--rose-primary, #D45E52)",
  letterSpacing: "-0.02em",
  minWidth: 78,
};
const compatScoreLabelStyle = {
  fontFamily: "'Inter', sans-serif",
  fontSize: 11,
  fontWeight: 700,
  letterSpacing: "0.14em",
  textTransform: "uppercase",
  color: "var(--plum-mute, #6b4a56)",
  margin: "0 0 4px",
};
const compatScoreDescStyle = {
  fontFamily: "'Fraunces', serif",
  fontStyle: "italic",
  fontSize: 16,
  color: "var(--plum-deep, #2b1e16)",
  margin: 0,
};
const compatNarrativeStyle = {
  fontFamily: "'Inter', sans-serif",
  fontSize: 13.5,
  lineHeight: 1.6,
  color: "var(--plum-mute, #6b4a56)",
  margin: "0 0 16px",
};
const dimsRowStyle = {
  display: "grid",
  gridTemplateColumns: "repeat(4, 1fr)",
  gap: 12,
};
const dimCellStyle = { display: "flex", flexDirection: "column", alignItems: "center", gap: 6 };
const dimBarStyle = {
  width: "100%",
  height: 5,
  borderRadius: 999,
  background: "var(--cream-2, rgba(43,30,22,0.08))",
  overflow: "hidden",
};
const dimFillStyle = {
  height: "100%",
  background: "linear-gradient(90deg, var(--rose-primary, #D45E52), var(--gold, #B89E6A))",
  borderRadius: 999,
};
const dimLabelStyle = {
  fontFamily: "'Inter', sans-serif",
  fontSize: 10,
  fontWeight: 700,
  letterSpacing: "0.12em",
  textTransform: "uppercase",
  color: "var(--plum-mute, #6b4a56)",
  margin: 0,
};
const dimValStyle = {
  fontFamily: "'Fraunces', serif",
  fontSize: 16,
  fontWeight: 500,
  color: "var(--plum-deep, #2b1e16)",
  margin: 0,
};

// Onboarding
const onboardingStyle = {
  position: "relative",
  overflow: "hidden",
  borderRadius: 22,
  padding: "40px 28px",
  textAlign: "center",
  color: "var(--cream, #FAF4EA)",
  background: "radial-gradient(circle at 30% 20%, #3a2a4c 0%, #221a2e 60%, #15101e 100%)",
  boxShadow: "0 2px 4px rgba(43,30,22,0.10), 0 12px 32px rgba(43,30,22,0.18)",
};
const onboardingGradientStyle = {
  position: "absolute", inset: 0,
  background:
    "radial-gradient(circle at 85% 15%, rgba(232,196,208,0.22) 0%, rgba(232,196,208,0) 30%)," +
    "radial-gradient(circle at 10% 80%, rgba(150,120,180,0.20) 0%, rgba(150,120,180,0) 35%)",
  pointerEvents: "none",
};
const onboardingTitleStyle = {
  position: "relative",
  fontFamily: "'Fraunces', serif",
  fontWeight: 300,
  fontSize: 30,
  color: "var(--cream, #FAF4EA)",
  margin: "16px 0 10px",
  letterSpacing: "-0.01em",
};
const onboardingBodyStyle = {
  position: "relative",
  fontFamily: "'Inter', sans-serif",
  fontSize: 14,
  lineHeight: 1.6,
  color: "rgba(247,239,225,0.84)",
  margin: "0 auto 20px",
  maxWidth: 380,
};
const onboardingBtnStyle = {
  position: "relative",
  fontFamily: "'Inter', sans-serif",
  fontWeight: 600,
  fontSize: 14,
  color: "var(--cream, #FAF4EA)",
  background: "var(--rose-primary, #D45E52)",
  border: "none",
  borderRadius: 9999,
  padding: "12px 22px",
  cursor: "pointer",
  minHeight: 44,
  boxShadow: "0 2px 8px rgba(212,94,82,0.30)",
};

// Keep these imports alive for tooling that strips unused exports.
void Lock;
void ALL_ZODIAC;
