// JessDailyOpener — Jess v2 J2-1
//
// One-per-day greeting that slides in from the top of the Planner.
// Phase-aware text generated by `callJessAgent` and cached daily under
// `jess_daily_open_<userId>_<YYYY-MM-DD>`. Auto-dismisses after 10s,
// or earlier when the user taps ×.
//
// No "Not medical advice" disclaimer — this is a greeting, not advice.

import { useEffect, useRef, useState } from "react";
import { X, Sparkles } from "lucide-react";
import {
  callJessAgent,
  loadDailyCache,
  saveDailyCache,
  todayKey,
} from "@/services/jessAgentService";
import { useCycleDay } from "@/hooks/useCycleDay";

const C = {
  cream:    "#F4EDDB",
  paperHi:  "#EDE6D5",
  espresso: "#3A2C1A",
  muted:    "#9B8B7A",
  gold:     "#D4AF37",
  blush:    "#E8B4B8",
  border:   "#D4C9B4",
};

const PHASE_FALLBACK = {
  menstrual:  "Good morning. Day {n} of your menstrual phase — be soft with yourself today.",
  follicular: "Good morning. Day {n} of your follicular phase — energy is on the way up.",
  ovulatory:  "Good morning. Day {n} of your ovulatory phase — your peak window is open.",
  luteal:     "Good morning. Day {n} of your luteal phase — a gentler pace suits this week.",
};

export default function JessDailyOpener({ user, profile }) {
  const { phase, cycleDay } = useCycleDay(profile);
  const lifeStage = profile?.life_stage || "reproductive";

  const [text, setText] = useState("");
  const [visible, setVisible] = useState(true);
  const [dismissing, setDismissing] = useState(false);
  const triedRef = useRef(false);
  const autoDismissRef = useRef(null);

  const cacheKey = user?.id ? `jess_daily_open_${user.id}_${todayKey()}` : null;

  useEffect(() => {
    if (!cacheKey || triedRef.current) return;
    triedRef.current = true;

    // If we already rendered today's opener, don't show it again.
    const cached = loadDailyCache(cacheKey);
    if (cached?.shown) {
      setVisible(false);
      return;
    }

    // Cache hit on text only — re-use, mark shown.
    if (cached?.text) {
      setText(cached.text);
      saveDailyCache(cacheKey, { ...cached, shown: true });
      scheduleAutoDismiss();
      return;
    }

    // Fresh fetch.
    const fallback = (PHASE_FALLBACK[phase] || PHASE_FALLBACK.follicular)
      .replace("{n}", String(cycleDay || 1));

    const system =
      "You are Jess, a warm UK-based women's health companion. " +
      "Write a warm 1-2 sentence good morning message that acknowledges " +
      "where they are in their cycle. Be warm, specific, not generic. " +
      "No medical advice. No sign-off. No quotation marks. " +
      "Maximum 220 characters.";

    const userPrompt =
      `Cycle day: ${cycleDay || 1}.\n` +
      `Phase: ${phase || "follicular"}.\n` +
      `Life stage: ${lifeStage}.\n\n` +
      `Write the greeting.`;

    callJessAgent({ system, user: userPrompt })
      .then(({ text: raw }) => {
        // Strip any ```code fences``` (incl. ```options blocks) the model
        // sometimes leaks, plus a trailing JSON action envelope.
        const stripped = String(raw || "")
          .replace(/```[\s\S]*?```/g, "")           // fenced blocks
          .replace(/\{[\s\S]*"actions"[\s\S]*\}\s*$/m, "") // trailing JSON envelope
          .trim()
          .replace(/^["']|["']$/g, "");
        const final = stripped && stripped.length > 8 ? stripped : fallback;
        setText(final);
        saveDailyCache(cacheKey, { text: final, shown: true });
        scheduleAutoDismiss();
      })
      .catch(() => {
        setText(fallback);
        saveDailyCache(cacheKey, { text: fallback, shown: true });
        scheduleAutoDismiss();
      });
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [cacheKey, phase, cycleDay, lifeStage]);

  function scheduleAutoDismiss() {
    if (autoDismissRef.current) clearTimeout(autoDismissRef.current);
    autoDismissRef.current = setTimeout(() => beginDismiss(), 10000);
  }

  function beginDismiss() {
    setDismissing(true);
    setTimeout(() => setVisible(false), 320);
    if (autoDismissRef.current) {
      clearTimeout(autoDismissRef.current);
      autoDismissRef.current = null;
    }
  }

  useEffect(() => () => {
    if (autoDismissRef.current) clearTimeout(autoDismissRef.current);
  }, []);

  if (!visible) return null;
  if (!text) return null; // wait for agent / cache before flashing

  const phaseLabel = phase ? phase.charAt(0).toUpperCase() + phase.slice(1) : "";

  return (
    <article style={{
      margin: "10px 16px 14px",
      background: `linear-gradient(135deg, ${C.paperHi} 0%, rgba(232,180,184,0.30) 100%)`,
      border: `1px solid ${C.border}`,
      borderLeft: `3px solid ${C.gold}`,
      borderRadius: 16,
      padding: "13px 14px 12px",
      display: "flex", alignItems: "flex-start", gap: 12,
      boxShadow: "0 6px 18px rgba(58,44,26,0.10)",
      animation: dismissing
        ? "jess-opener-leave 320ms ease-in forwards"
        : "jess-opener-enter 380ms cubic-bezier(0.16,1,0.3,1)",
    }}>
      <div style={{
        width: 32, height: 32, borderRadius: 9999,
        background: C.gold,
        display: "inline-flex", alignItems: "center", justifyContent: "center",
        flexShrink: 0, marginTop: 1,
      }} aria-hidden>
        <Sparkles size={15} style={{ color: C.espresso }} />
      </div>
      <div style={{ flex: 1, minWidth: 0 }}>
        <p style={{
          margin: 0, fontSize: 10, fontWeight: 700,
          letterSpacing: "0.16em", textTransform: "uppercase",
          color: C.muted, fontFamily: "'Inter', sans-serif",
        }}>Jess · Good morning</p>
        <p style={{
          margin: "4px 0 0", fontSize: 14,
          fontFamily: "'Fraunces', Georgia, serif",
          color: C.espresso, lineHeight: 1.5,
        }}>{String(text || "").replace(/```[\s\S]*?```/g, "").replace(/\{[\s\S]*"actions"[\s\S]*\}\s*$/m, "").trim() || text}</p>
        {(phase || cycleDay) && (
          <p style={{
            margin: "4px 0 0", fontSize: 11, color: C.muted,
            fontFamily: "'Inter', sans-serif", letterSpacing: "0.02em",
          }}>{cycleDay ? `Day ${cycleDay}` : ""}{cycleDay && phaseLabel ? " · " : ""}{phaseLabel}</p>
        )}
      </div>
      <button
        type="button"
        onClick={beginDismiss}
        aria-label="Dismiss greeting"
        style={{
          width: 26, height: 26, borderRadius: 9999,
          background: "rgba(58,44,26,0.06)", border: "none",
          color: C.espresso, cursor: "pointer",
          display: "inline-flex", alignItems: "center", justifyContent: "center",
          flexShrink: 0, padding: 0,
        }}
      ><X size={12} /></button>
      <style>{`
        @keyframes jess-opener-enter {
          from { opacity: 0; transform: translateY(-12px); }
          to   { opacity: 1; transform: translateY(0); }
        }
        @keyframes jess-opener-leave {
          from { opacity: 1; transform: translateY(0); }
          to   { opacity: 0; transform: translateY(-8px); }
        }
      `}</style>
    </article>
  );
}
