// ─────────────────────────────────────────────────────────────────────────────
// GpExportButton — STEP 7 of the Life Stage build.
//
// "Export for GP" one-tap PDF available on the Cycle tab for:
//   - Perimenopause / menopause (life_stage matches)
//   - Reproductive years
//   - Postpartum
//
// Builds a 1-page A4 PDF from data the user already has:
//   - User name + current life stage + date range
//   - Top symptoms by frequency (from DailyCheckins / MenopauseDailyLog)
//   - Cycle summary (last period start, average length, if relevant)
//   - Mean mood + mean sleep over the window
//   - Active HRT regimen (if logged)
//   - Footer disclaimer
//
// Footer line (per Halli's spec):
//   "Generated by Femwell · Not a medical record · For GP conversation use"
//
// Uses jsPDF (already in package.json) — no new dependency.
//
// This is a *separate* surface from DoctorReadyDiaryCard (which is the
// fuller NICE NG23 diary, mounted via the `doctor` cycle anchor). The GP
// export is the lighter, life-stage-aware variant we ship across more stages.
// ─────────────────────────────────────────────────────────────────────────────

import { useState } from "react";
import { base44 } from "@/api/base44Client";
import { FileText, Loader2 } from "lucide-react";
import jsPDF from "jspdf";

const WINDOW_DAYS = 42; // 6 weeks

const LIFE_STAGE_LABEL = {
  teen:             "Teen",
  reproductive:     "Reproductive years",
  "pre-ttc":        "Pre-TTC",
  ttc:              "Trying to conceive",
  "pregnant-t1":    "Pregnant — Trimester I",
  "pregnant-t2":    "Pregnant — Trimester II",
  "pregnant-t3":    "Pregnant — Trimester III",
  pregnancy:        "Pregnant",
  postpartum:       "Postpartum",
  perimenopause:    "Perimenopause",
  menopause:        "Menopause",
  "post-menopause": "Post-menopause",
  none:             "Not specified",
};

const ELIGIBLE_STAGES = new Set([
  "reproductive",
  "perimenopause",
  "menopause",
  "postpartum",
]);

function fmtDate(d) {
  if (!d) return "—";
  const dt = d instanceof Date ? d : new Date(d);
  if (Number.isNaN(dt.getTime())) return "—";
  return dt.toLocaleDateString("en-GB", { day: "2-digit", month: "short", year: "numeric" });
}

function avgOf(rows, field) {
  const xs = (rows || [])
    .map((r) => Number(r?.[field]))
    .filter((n) => Number.isFinite(n));
  if (xs.length === 0) return null;
  const mean = xs.reduce((a, b) => a + b, 0) / xs.length;
  return Math.round(mean * 10) / 10;
}

function countOf(rows, field, minVal = 1) {
  return (rows || []).filter((r) => {
    const v = Number(r?.[field]);
    return Number.isFinite(v) && v >= minVal;
  }).length;
}

function isWithinWindow(iso, fromISO, toISO) {
  return iso && iso >= fromISO && iso <= toISO;
}

// Safe fetch — returns [] when the entity is missing on base44 (e.g. the
// schema migration hasn't shipped yet) or when the SDK call throws / rejects.
function safeFilter(entityName, args) {
  try {
    const ent = base44?.entities?.[entityName];
    if (!ent || typeof ent.filter !== "function") return Promise.resolve([]);
    return ent.filter(...args).catch(() => []);
  } catch {
    return Promise.resolve([]);
  }
}

async function buildSnapshot(profile, plannerConfig) {
  const userId = profile?.user_id;
  if (!userId) return null;
  const today = new Date();
  const from = new Date(today);
  from.setDate(today.getDate() - WINDOW_DAYS);
  const fromISO = from.toISOString().split("T")[0];
  const toISO = today.toISOString().split("T")[0];

  const [dailyAll, menoAll, hrtAll] = await Promise.all([
    safeFilter("DailyCheckins",       [{ user_id: userId }, "-date",       200]),
    safeFilter("MenopauseDailyLog",   [{ user_id: userId }, "-date",       200]),
    safeFilter("HrtLog",              [{ user_id: userId }, "-start_date",  10]),
  ]);

  const daily = (Array.isArray(dailyAll) ? dailyAll : []).filter((r) => isWithinWindow(r?.date, fromISO, toISO));
  const meno = (Array.isArray(menoAll) ? menoAll : []).filter((r) => isWithinWindow(r?.date, fromISO, toISO));
  const hrt = (Array.isArray(hrtAll) ? hrtAll : []).find((r) => r?.is_active !== false) || null;

  return {
    range: { from: fromISO, to: toISO, days: WINDOW_DAYS },
    profile,
    plannerConfig,
    daily,
    meno,
    hrt,
  };
}

function buildPdf(snap, displayName) {
  const pdf = new jsPDF({ unit: "pt", format: "a4" });
  const margin = 48;
  const pageW = 595.28;
  const innerW = pageW - margin * 2;
  let y = margin;

  const heading = (size) => { pdf.setFont("helvetica", "bold"); pdf.setFontSize(size); };
  const body = (size) => { pdf.setFont("helvetica", "normal"); pdf.setFontSize(size); };
  const italic = (size) => { pdf.setFont("helvetica", "italic"); pdf.setFontSize(size); };

  // Header
  heading(20);
  pdf.text("Femwell — GP-ready summary", margin, y); y += 24;

  body(10.5);
  const stageLabel = LIFE_STAGE_LABEL[snap.profile?.life_stage] || "Not specified";
  pdf.text(`Patient: ${displayName || "—"}`, margin, y); y += 14;
  pdf.text(`Current life stage: ${stageLabel}`, margin, y); y += 14;
  const conditions = (snap.profile?.conditions || snap.profile?.condition_flags || []).join(", ") || "none logged";
  pdf.text(`Conditions: ${conditions}`, margin, y); y += 14;
  pdf.text(`Reporting window: ${fmtDate(snap.range.from)} → ${fmtDate(snap.range.to)}  (${snap.range.days} days)`, margin, y); y += 18;

  pdf.setDrawColor(168, 134, 75);
  pdf.setLineWidth(0.5);
  pdf.line(margin, y, pageW - margin, y); y += 18;

  // ── Top symptoms by frequency ────────────────────────────────────────────
  heading(13);
  pdf.text("Top symptoms by frequency", margin, y); y += 18;
  body(11);

  const stage = snap.profile?.life_stage;
  const isPeriMeno = stage === "perimenopause" || stage === "menopause";

  if (isPeriMeno) {
    const flushDays = countOf(snap.meno, "hot_flashes", 1);
    const heavyFlushDays = countOf(snap.meno, "hot_flashes", 3);
    const sweatDays = countOf(snap.meno, "night_sweats", 1);
    const brainFogDays = countOf(snap.meno, "brain_fog", 3);
    const jointDays = countOf(snap.meno, "joint_pain", 3);
    const lines = [
      `Hot flushes (≥1 per day): ${flushDays} day${flushDays === 1 ? "" : "s"}  ·  (≥3 per day): ${heavyFlushDays}`,
      `Night sweats: ${sweatDays} day${sweatDays === 1 ? "" : "s"}`,
      `Brain fog (≥3/10): ${brainFogDays} day${brainFogDays === 1 ? "" : "s"}`,
      `Joint pain (≥3/10): ${jointDays} day${jointDays === 1 ? "" : "s"}`,
    ];
    for (const ln of lines) { pdf.text(ln, margin, y); y += 14; }
    if (snap.meno.length === 0) {
      italic(11);
      pdf.text("No menopause symptom logs in window.", margin, y); y += 14;
      body(11);
    }
  } else {
    // Reproductive / postpartum — derive from DailyCheckins.
    const meanMood = avgOf(snap.daily, "mood");
    const meanEnergy = avgOf(snap.daily, "energy");
    const meanFocus = avgOf(snap.daily, "focus");
    const lowMoodDays = (snap.daily || []).filter((r) => Number(r?.mood) > 0 && Number(r?.mood) <= 2).length;
    const lines = [
      `Days logged in window: ${snap.daily.length}`,
      `Days with low mood (≤2/5): ${lowMoodDays}`,
      `Mean mood: ${meanMood ?? "—"} / 5  ·  Mean energy: ${meanEnergy ?? "—"} / 5${meanFocus ? `  ·  Mean focus: ${meanFocus} / 5` : ""}`,
    ];
    for (const ln of lines) { pdf.text(ln, margin, y); y += 14; }
    if (snap.daily.length === 0) {
      italic(11);
      pdf.text("No daily check-ins in window.", margin, y); y += 14;
      body(11);
    }
  }
  y += 8;

  // ── Cycle summary ────────────────────────────────────────────────────────
  heading(13);
  pdf.text("Cycle summary", margin, y); y += 18;
  body(11);
  const lastPeriod = snap.profile?.last_period_start_date;
  const avgLen = snap.profile?.cycle_avg_length;
  const periodLen = snap.profile?.period_length;
  const cyclesObserved = snap.profile?.cycle_prediction_meta?.cycles_observed || 0;
  const conf = snap.profile?.cycle_prediction_meta?.confidence_pct;

  if (lastPeriod) {
    pdf.text(`Last period start: ${fmtDate(lastPeriod)}`, margin, y); y += 14;
    if (avgLen) { pdf.text(`Average cycle length: ${avgLen} days  ·  Average period length: ${periodLen || "—"} days`, margin, y); y += 14; }
    if (cyclesObserved >= 0) {
      pdf.text(`Cycles observed by app: ${cyclesObserved}  ${conf ? `·  Prediction confidence: ${Math.round(conf)}%` : ""}`, margin, y); y += 14;
    }
  } else {
    italic(11);
    pdf.text(isPeriMeno
      ? "Cycle no longer the primary frame — see symptom and HRT sections."
      : "No period start logged yet.", margin, y);
    y += 14;
    body(11);
  }
  y += 8;

  // ── Mood + sleep averages ────────────────────────────────────────────────
  heading(13);
  pdf.text("Mood + sleep averages", margin, y); y += 18;
  body(11);
  const sleepHours = avgOf(snap.daily, "sleep_hours");
  const sleepQual = avgOf(snap.daily, "sleep_quality");
  const moodAvg = avgOf(snap.daily, "mood");
  const lines = [
    `Mean sleep duration: ${sleepHours ?? "—"} hours/night`,
    `Mean sleep quality: ${sleepQual ?? "—"} / 5`,
    `Mean mood: ${moodAvg ?? "—"} / 5`,
  ];
  for (const ln of lines) { pdf.text(ln, margin, y); y += 14; }
  y += 8;

  // ── HRT ──────────────────────────────────────────────────────────────────
  heading(13);
  pdf.text("HRT in use", margin, y); y += 18;
  body(11);
  if (snap.hrt) {
    pdf.text(`Type: ${snap.hrt.type || "—"}`, margin, y); y += 14;
    if (snap.hrt.dose)       { pdf.text(`Dose: ${snap.hrt.dose}`, margin, y); y += 14; }
    if (snap.hrt.route)      { pdf.text(`Route: ${snap.hrt.route}`, margin, y); y += 14; }
    if (snap.hrt.start_date) { pdf.text(`Started: ${fmtDate(snap.hrt.start_date)}`, margin, y); y += 14; }
    if (snap.hrt.notes)      {
      const wrapped = pdf.splitTextToSize(`Notes: ${snap.hrt.notes}`, innerW);
      pdf.text(wrapped, margin, y); y += wrapped.length * 14;
    }
  } else {
    italic(11);
    pdf.text("No HRT regimen logged.", margin, y); y += 14;
    body(11);
  }
  y += 12;

  // ── Footer ───────────────────────────────────────────────────────────────
  pdf.setDrawColor(168, 134, 75);
  pdf.line(margin, y, pageW - margin, y); y += 16;
  italic(9.5);
  pdf.text("Generated by Femwell · Not a medical record · For GP conversation use", margin, y);
  body(9);
  pdf.text(`Generated ${fmtDate(new Date())}`, margin, y + 12);

  return pdf;
}

export default function GpExportButton({ profile, plannerConfig, effectiveLifeStage }) {
  const [status, setStatus] = useState("idle"); // idle | loading | done | error
  const [errorMsg, setErrorMsg] = useState(null);

  // Eligibility: per Halli's spec, peri / reproductive / postpartum +
  // menopause. Prefer the effective life stage (which honours the
  // DevStageSwitcher localStorage override) over the raw profile value
  // so the dev-only preview path shows the export card too.
  const stage = effectiveLifeStage || profile?.life_stage;
  if (!ELIGIBLE_STAGES.has(stage) && stage !== "menopause") {
    return null;
  }

  const handleExport = async () => {
    if (status === "loading") return;
    setStatus("loading");
    setErrorMsg(null);
    try {
      const snap = await buildSnapshot(profile, plannerConfig);
      if (!snap) {
        setStatus("error");
        setErrorMsg("No profile loaded yet.");
        return;
      }
      const displayName = profile?.display_name || profile?.user_email || "Femwell user";
      // Wrap the jsPDF call separately — if the lib fails (rare, but the
      // Promise from buildSnapshot already swallowed entity-missing errors),
      // surface a friendly toast rather than crashing the page.
      let pdf;
      try {
        pdf = buildPdf(snap, displayName);
      } catch (pdfErr) {
        setStatus("error");
        setErrorMsg("Export unavailable until schema is migrated.");
        console.warn("[GpExportButton] PDF build failed:", pdfErr);
        return;
      }
      const dateStamp = new Date().toISOString().split("T")[0];
      const safeName = (displayName || "femwell").replace(/[^a-z0-9]+/gi, "-").toLowerCase();
      pdf.save(`gp-summary-${safeName}-${dateStamp}.pdf`);
      setStatus("done");
      setTimeout(() => setStatus("idle"), 3000);
    } catch (err) {
      setStatus("error");
      setErrorMsg(String(err?.message || err));
    }
  };

  return (
    <section style={wrap} aria-label="GP-ready summary export">
      <header style={headRow}>
        <div>
          <div style={eyebrow}>FOR YOUR GP · ONE-PAGE</div>
          <div style={titleStyle}>Export for GP</div>
          <p style={hintStyle}>
            A printable summary of the last 6 weeks of {LIFE_STAGE_LABEL[stage] || "Femwell"} data — top symptoms, cycle, sleep, mood, HRT if logged. Hand it to your GP at your next appointment.
          </p>
        </div>
      </header>

      <button
        type="button"
        onClick={handleExport}
        disabled={status === "loading"}
        aria-label="Export GP-ready summary as PDF"
        style={{ ...exportBtn, opacity: status === "loading" ? 0.7 : 1 }}
      >
        {status === "loading" ? (
          <>
            <Loader2 size={13} strokeWidth={2.2} className="gp-spin" />
            <span>Building…</span>
          </>
        ) : (
          <>
            <FileText size={13} strokeWidth={2.2} />
            <span>Export PDF</span>
          </>
        )}
      </button>

      {status === "done" && (
        <p style={successHint}>Saved to your downloads.</p>
      )}
      {status === "error" && errorMsg && (
        <p style={errorHint}>Could not build the PDF: {errorMsg}</p>
      )}

      <style>{`
        .gp-spin { animation: gp-spin 0.9s linear infinite; }
        @keyframes gp-spin { from { transform: rotate(0deg); } to { transform: rotate(360deg); } }
        @media (prefers-reduced-motion: reduce) { .gp-spin { animation: none; } }
      `}</style>
    </section>
  );
}

// ─── Styles ─────────────────────────────────────────────────────────────────
const wrap = {
  background: "#FBF6E6",
  border: "1px solid rgba(58,44,26,0.10)",
  borderRadius: 16,
  padding: "16px 14px",
  marginBottom: 14,
};
const headRow = {
  marginBottom: 10,
};
const eyebrow = {
  fontFamily: "'Inter', system-ui, sans-serif",
  fontSize: 9.5,
  fontWeight: 700,
  letterSpacing: "0.18em",
  color: "#A6862B",
  textTransform: "uppercase",
};
const titleStyle = {
  fontFamily: "'Fraunces', Georgia, serif",
  fontSize: 18,
  fontWeight: 500,
  color: "#3A2C1A",
  fontStyle: "italic",
  margin: "3px 0 6px",
  letterSpacing: "-0.01em",
};
const hintStyle = {
  fontFamily: "'Inter', system-ui, sans-serif",
  fontSize: 12.5,
  color: "#6B5840",
  lineHeight: 1.5,
  margin: 0,
};
const exportBtn = {
  display: "inline-flex",
  alignItems: "center",
  gap: 6,
  padding: "10px 16px",
  background: "#3A2C1A",
  color: "#F4EDDB",
  border: "none",
  borderRadius: 9999,
  fontFamily: "'Inter', system-ui, sans-serif",
  fontSize: 12.5,
  fontWeight: 700,
  letterSpacing: "0.06em",
  cursor: "pointer",
  marginTop: 4,
};
const successHint = {
  marginTop: 8,
  fontFamily: "Georgia, serif",
  fontStyle: "italic",
  fontSize: 12,
  color: "#6B8F5A",
};
const errorHint = {
  marginTop: 8,
  fontFamily: "Georgia, serif",
  fontStyle: "italic",
  fontSize: 12,
  color: "#D45E52",
};
