import React from 'react';
import {beforeEach,afterEach,it,expect,vi} from 'vitest';
import {render,screen,fireEvent,waitFor,within} from '@testing-library/react';
const data=vi.hoisted(()=>({state:null,selected:vi.fn(),filter:vi.fn(async()=>[]),create:vi.fn(),update:vi.fn(),invoke:vi.fn(),progress:vi.fn(),refresh:vi.fn()}));
vi.mock('@/components/lifestyle-elite/sky/useSelectedSkyChart',()=>({default:(...args)=>{data.selected(...args);return data.state;}}));
vi.mock('@/components/lifestyle-elite/sky/useSkyCompletion',()=>({default:()=>({letter:null,unlocked:false,rw:null,loading:false,letterError:'',cycleError:'',retry:vi.fn()})}));
vi.mock('@/components/horoscope/hooks/useBirthChart',()=>({useBirthChart:()=>data.state}));
vi.mock('@/components/horoscope/hooks/useProfections',()=>({default:()=>({profection:null,saturn:null})}));
vi.mock('@/components/horoscope/hooks/useAsteroids',()=>({default:()=>({ceres:'Virgo'})}));
vi.mock('@/components/community/readingActivity',()=>({recordProgress:data.progress,hasReadLocally:()=>false}));
vi.mock('@/api/base44Client',()=>({base44:{auth:{me:vi.fn(async()=>({id:'a'}))},entities:new Proxy({},{get:(_,name)=>({filter:(...args)=>data.filter(name,...args),create:data.create,update:data.update,subscribe:()=>()=>{}})}),functions:{invoke:data.invoke}}}));
import SkyFocus from './SkyFocus';
import {FirstFoldSummary} from './FirstFold';
const props={artDirection:'sky-worlds',direction:'petal-press',continuous:true,celestial:true,dailyLessons:true,contentRoute:'/CalmLifestyleDemo',focusedPreview:true,calmLayout:true};
function roomState(owner='a'){return {user:{id:owner},astro:{id:'chart-'+owner,user_id:owner,birth_date:'1997-06-17',sun_sign:'Gemini',moon_sign:'Libra',rising_sign:'Virgo'},reading:{id:'reading-'+owner,user_id:owner,reading_date:'2026-10-09',headline:'An actual source',narrative:'Full source first paragraph.\n\nSecond source paragraph, never removed.'},userProfile:{user_id:owner},loading:false,generatingReading:false,refreshing:false,exactReading:false,error:'',setAstro:vi.fn(),refresh:data.refresh};}
function calls(name){return data.filter.mock.calls.filter(call=>call[0]===name);}
beforeEach(()=>{vi.clearAllMocks();data.filter.mockResolvedValue([]);data.state=roomState();window.history.replaceState({},'','/CalmLifestyleDemo?section=sky');Object.defineProperty(HTMLDialogElement.prototype,'showModal',{configurable:true,value:vi.fn(function(){this.setAttribute('open','');})});Object.defineProperty(HTMLDialogElement.prototype,'close',{configurable:true,value:vi.fn(function(){this.removeAttribute('open');})});Object.defineProperty(HTMLElement.prototype,'scrollIntoView',{configurable:true,value:vi.fn()});});
afterEach(()=>{expect(data.create).not.toHaveBeenCalled();expect(data.update).not.toHaveBeenCalled();expect(data.invoke).not.toHaveBeenCalled();expect(data.progress).not.toHaveBeenCalled();vi.restoreAllMocks();});
it('defers optional histories and settings until first use without losing the daily lesson',async()=>{render(<SkyFocus {...props}/>);await waitFor(()=>expect(calls('SavedItems').length).toBeGreaterThan(0));['AdviceThreads','AdviceMessages','SkyNote','UserPreferences','HoroscopeReading'].forEach(name=>expect(calls(name)).toHaveLength(0));expect(screen.getByRole('button',{name:'Next sky lesson'})).toBeEnabled();fireEvent.click(screen.getByRole('button',{name:/Sky diary/}));await waitFor(()=>expect(calls('SkyNote')).toHaveLength(1));expect(calls('HoroscopeReading')).toHaveLength(1);expect(calls('AdviceThreads')).toHaveLength(0);fireEvent.click(within(screen.getByRole('dialog',{name:'Sky diary'})).getByRole('button',{name:'Close'}));fireEvent.click(screen.getByRole('button',{name:/Sky diary/}));expect(calls('SkyNote')).toHaveLength(1);expect(calls('HoroscopeReading')).toHaveLength(1);});
it('keeps the real Ask draft through close/reopen and route suspension without refetching history',async()=>{const outside=document.createElement('button');outside.textContent='Other route';document.body.append(outside);const {rerender}=render(<SkyFocus {...props}/>);const open=screen.getByRole('button',{name:/Ask the sky.*Your questions/});open.focus();fireEvent.click(open);await waitFor(()=>expect(calls('AdviceThreads')).toHaveLength(1));fireEvent.change(screen.getByRole('textbox',{name:'Your question for the sky'}),{target:{value:'Actual retained words'}});fireEvent.click(within(screen.getByRole('dialog',{name:'Ask the sky'})).getByRole('button',{name:'Close'}));expect(open).toHaveFocus();fireEvent.click(open);expect(screen.getByRole('textbox',{name:'Your question for the sky'})).toHaveValue('Actual retained words');outside.focus();rerender(<SkyFocus {...props} routeActive={false}/>);expect(screen.queryByRole('dialog')).not.toBeInTheDocument();expect(outside).toHaveFocus();rerender(<SkyFocus {...props} routeActive/>);expect(screen.getByRole('textbox',{name:'Your question for the sky'})).toHaveValue('Actual retained words');expect(calls('AdviceThreads')).toHaveLength(1);outside.remove();});
it('the focused Ask action opens the real task on first use',async()=>{const handled=vi.fn();render(<SkyFocus {...props} actionRequest={{type:'ask'}} onActionHandled={handled}/>);expect(screen.getByRole('dialog',{name:'Ask the sky'})).toBeVisible();expect(screen.getByRole('textbox',{name:'Your question for the sky'})).toBeEnabled();expect(handled).toHaveBeenCalledWith(null);await waitFor(()=>expect(calls('AdviceThreads')).toHaveLength(1));});
it('a visited Ask task cannot retain the former owner draft after account change',async()=>{const {rerender}=render(<SkyFocus {...props}/>);fireEvent.click(screen.getByRole('button',{name:/Ask the sky.*Your questions/}));fireEvent.change(screen.getByRole('textbox',{name:'Your question for the sky'}),{target:{value:'Account A words'}});data.state=roomState('b');rerender(<SkyFocus {...props}/>);expect(screen.getByRole('textbox',{name:'Your question for the sky'})).toHaveValue('');await waitFor(()=>expect(calls('AdviceThreads').some(call=>call[1].user_id==='b')).toBe(true));});
it('keeps every glance action and the full Jess source accessible in the calm fold',()=>{const calls=[vi.fn(),vi.fn(),vi.fn()];const Icon=()=>null;function Harness(){const [open,setOpen]=React.useState(false);return <FirstFoldSummary calmLayout orderedGlance={calls.map((fn,i)=>({Icon,label:'Actual glance '+i,text:'Exact row '+i,onClick:fn}))} jess={{eyebrow:'Jess',body:'Brief'}} sheetSections={[{label:'Full source',text:'All of Jess’s substantive read.'}]} jessOpen={open} onJessOpen={()=>setOpen(true)} onJessClose={()=>setOpen(false)}/>;}render(<Harness/>);fireEvent.click(screen.getByRole('button',{name:/Actual glance 0.*Exact row 0/}));fireEvent.click(screen.getByText('Elsewhere today'));fireEvent.click(screen.getByRole('button',{name:/Actual glance 2.*Exact row 2/}));expect(calls[0]).toHaveBeenCalledOnce();expect(calls[2]).toHaveBeenCalledOnce();fireEvent.click(screen.getByRole('button',{name:'Jess’s read'}));fireEvent.click(screen.getByRole('button',{name:'Open Jess’s full read'}));expect(screen.getByText('All of Jess’s substantive read.')).toBeVisible();fireEvent.click(within(screen.getByRole('dialog',{name:'Jess’s read'})).getByRole('button',{name:'Close'}));expect(screen.getByRole('button',{name:'Open Jess’s full read'})).toHaveFocus();});
it('a copied compatibility arrival opens its actual pairing directly',()=>{window.history.replaceState({},'','/CalmLifestyleDemo?section=sky&compat='+encodeURIComponent(JSON.stringify({name:'An actual friend',birthday:'1991-02-03'})));render(<SkyFocus {...props}/>);expect(screen.getByRole('dialog',{name:'You & someone'})).toBeVisible();expect(screen.getByRole('textbox',{name:'Their name'})).toHaveValue('An actual friend');});
it('an explicit diary arrival still reaches the diary when no current chart exists',()=>{data.state={...roomState(),astro:null,reading:null};const handled=vi.fn();render(<SkyFocus {...props} actionRequest={{type:'diary'}} onActionHandled={handled}/>);expect(screen.getByRole('dialog',{name:'Sky diary'})).toBeVisible();expect(screen.getByTestId('observed-sky-diary')).toBeVisible();expect(handled).toHaveBeenCalledWith(null);});
it.each(['petal-press','workbench'])('keeps the actual Moon field guide as closed support in the %s branch',async direction=>{render(<SkyFocus {...props} direction={direction}/>);const support=screen.getByText('Moon field guide').closest('details');expect(support).not.toHaveAttribute('open');expect(support.querySelector('summary')).toHaveTextContent('Moon field guide');expect(support.querySelectorAll('button')).toHaveLength(8);fireEvent.click(screen.getByText('Moon field guide'));expect(support).toHaveAttribute('open');await waitFor(()=>expect(data.filter).toHaveBeenCalled());});
it('keeps the actual daily lesson Community seed tied to the exact calm preview edition',async()=>{render(<SkyFocus {...props}/>);const link=screen.getByRole('link',{name:'Take this lesson to the lounge'});const seed=new URL(link.href).searchParams.get('seed');expect(seed).toContain('https://femwells.com/CalmLifestyleDemo?');expect(seed).toContain('section=sky');expect(seed).toContain('lessonVersion=1');expect(seed).not.toContain('LivingLifestyleDemo');const sourceUrl=seed.split('\n\n')[1];const target=new URL(sourceUrl);expect(target.hash).toBe('#daily-sky-lesson');expect(target.searchParams.get('lesson')).toBeTruthy();await waitFor(()=>expect(data.filter).toHaveBeenCalled());});
